### ISSUE TITLE
口罩分类

### ISSUE THREAD

**Issue by meloxuan** [lantegu/mask_facebox#1]
您好，我在跑了您的程序之后发现可以识别出人脸，但是并不能对戴口罩与否进行分类，请问这是由于什么原因吗？

**Comment by lantegu** [comment]
抱歉，这是当时学习用的，readme没写清楚。这是戴口罩下的人脸性别识别框架。

**Comment by meloxuan** [comment]
但是也不能对人脸性别进行检测呢；看到了您用的是MAFA，这是一个口罩检测数据集，而且将类别数目改成了3类，明显是不戴口罩，戴口罩和非人脸的，能否指引下呢，感谢
